### ISSUE TITLE
Seems as if custom formatters have now been realized in cucumber-js

### ISSUE THREAD

**Issue by silkentrance** [dtinteractive/cucumber-js-teamcity#1]
See https://github.com/cucumber/cucumber-js/issues/516

It seems that you have to

```
cucumber.js --format /path/to/custom/formatter.js ...
```

From what I gathered from

https://github.com/cucumber/cucumber-js/blob/master/src/formatter/builder.js#L47

https://github.com/cucumber/cucumber-js/blob/master/src/formatter/builder.js#L71

and here

https://github.com/cucumber/cucumber-js/blob/master/src/formatter/json_formatter.js

your formatter need some refactoring in order to work.

Do you require help/assistance?

**Comment by silkentrance** [comment]
closing: forget that, i will implement my own.

**Comment by NHKK** [comment]
Sorry this is a bit confusing for me. does this mean we have to place the formatter file in the src/formatter/myCustomformattter.js ? I looked at the custom formatter md file and tried to use the first example but unfortunately got an "import" token are there steps we need to take prior to making all of this work? is there an example of a successful implemented custom formatter not part of the cucumberjs library?

**Comment by silkentrance** [comment]
@NHKK I closed this because the existing code of this project does not support the official API.
